---
core:
	num_workers: 1000

inventory:
	plugin: nornir.plugins.inventory.simple.SimpleInventory
	options:
		host_file: "inventory/hosts.yaml"
		groups_file: "inventory/groups.yaml"
		defaults_file: "inventory/defaults.yaml"
